/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Sahrour
 */
public class AcceuilBestDeal extends javax.swing.JFrame {

    /**
     * Creates new form AcceuilBestDeal
     */
    public AcceuilBestDeal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        MPB4 = new javax.swing.JButton();
        MPB2 = new javax.swing.JButton();
        MPB1 = new javax.swing.JButton();
        MPB3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MenuMP = new javax.swing.JMenuBar();
        CompteMP = new javax.swing.JMenu();
        MCompteMP = new javax.swing.JMenuItem();
        DeconnexionMP = new javax.swing.JMenuItem();
        DReserverMP = new javax.swing.JMenu();
        LDReserverMP = new javax.swing.JMenuItem();
        helpMP = new javax.swing.JMenu();
        PresentationMP = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        MPB4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MPB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pub.jpg"))); // NOI18N
        MPB4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MPB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPB4ActionPerformed(evt);
            }
        });
        jPanel1.add(MPB4);
        MPB4.setBounds(460, 250, 225, 97);

        MPB2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MPB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.jpg"))); // NOI18N
        MPB2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MPB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPB2ActionPerformed(evt);
            }
        });
        jPanel1.add(MPB2);
        MPB2.setBounds(460, 110, 225, 97);

        MPB1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MPB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deale.jpg"))); // NOI18N
        MPB1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MPB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPB1ActionPerformed(evt);
            }
        });
        jPanel1.add(MPB1);
        MPB1.setBounds(40, 110, 225, 97);

        MPB3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MPB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/proposé.jpg"))); // NOI18N
        MPB3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MPB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPB3ActionPerformed(evt);
            }
        });
        jPanel1.add(MPB3);
        MPB3.setBounds(40, 250, 225, 97);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo (2).png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(240, 10, 259, 94);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg_top_img.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-6, 0, 730, 390);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(53, 36, 713, 383);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg_top_img.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 440);

        CompteMP.setText("Mon Compte");

        MCompteMP.setText("Mon Compte");
        MCompteMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCompteMPActionPerformed(evt);
            }
        });
        CompteMP.add(MCompteMP);

        DeconnexionMP.setText("Deconnexion");
        DeconnexionMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeconnexionMPActionPerformed(evt);
            }
        });
        CompteMP.add(DeconnexionMP);

        MenuMP.add(CompteMP);

        DReserverMP.setText("Deals Reserver");
        DReserverMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DReserverMPActionPerformed(evt);
            }
        });

        LDReserverMP.setText("Liste de Deals Reserver");
        LDReserverMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LDReserverMPActionPerformed(evt);
            }
        });
        DReserverMP.add(LDReserverMP);

        MenuMP.add(DReserverMP);

        helpMP.setText("?");
        helpMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMPActionPerformed(evt);
            }
        });

        PresentationMP.setText("Presentation");
        helpMP.add(PresentationMP);

        jMenuItem1.setText("Statistique");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        helpMP.add(jMenuItem1);

        MenuMP.add(helpMP);

        setJMenuBar(MenuMP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MCompteMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCompteMPActionPerformed
        // TODO add your handling code here:
        CompteAdmin c = new CompteAdmin();
          
        this.setVisible(false);
               c.setVisible(true); 
    }//GEN-LAST:event_MCompteMPActionPerformed

    private void DeconnexionMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeconnexionMPActionPerformed
        // TODO add your handling code here:
        ConnexionBestDeal cnx = new ConnexionBestDeal();
        this.setVisible(false);
        cnx.setVisible(true);
    }//GEN-LAST:event_DeconnexionMPActionPerformed

    private void DReserverMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DReserverMPActionPerformed
        // TODO add your handling code here:
       DealComander dr=new DealComander();
        this.setVisible(false);
        dr.setVisible(true);
    }//GEN-LAST:event_DReserverMPActionPerformed

    private void helpMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMPActionPerformed
        // TODO add your handling code here:
        Presentation p=new Presentation();
        this.setVisible(false);
        p.setVisible(true);
    }//GEN-LAST:event_helpMPActionPerformed

    private void LDReserverMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LDReserverMPActionPerformed
        // TODO add your handling code here:
         DealComander l=new DealComander();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_LDReserverMPActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         Statistique c = new Statistique();
        this.setVisible(false);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MPB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPB3ActionPerformed
        // TODO add your handling code here:
        ListDealProposé b=new ListDealProposé();
        this.setVisible(false);
        b.setVisible(true);
    }//GEN-LAST:event_MPB3ActionPerformed

    private void MPB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPB1ActionPerformed
        // TODO add your handling code here:
        MenuDeal deal=new MenuDeal();
        this.setVisible(false);
        deal.setVisible(true);
    }//GEN-LAST:event_MPB1ActionPerformed

    private void MPB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPB2ActionPerformed
        // TODO add your handling code here:
        MenuUtilisateur menuUser = new MenuUtilisateur();
        this.setVisible(false);
        menuUser.setVisible(true);
    }//GEN-LAST:event_MPB2ActionPerformed

    private void MPB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPB4ActionPerformed
        // TODO add your handling code here:
        EspacePub pub=new EspacePub();
        this.setVisible(false);
        pub.setVisible(true);
    }//GEN-LAST:event_MPB4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcceuilBestDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcceuilBestDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcceuilBestDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceuilBestDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcceuilBestDeal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CompteMP;
    private javax.swing.JMenu DReserverMP;
    private javax.swing.JMenuItem DeconnexionMP;
    private javax.swing.JMenuItem LDReserverMP;
    private javax.swing.JMenuItem MCompteMP;
    private javax.swing.JButton MPB1;
    private javax.swing.JButton MPB2;
    private javax.swing.JButton MPB3;
    private javax.swing.JButton MPB4;
    private javax.swing.JMenuBar MenuMP;
    private javax.swing.JMenuItem PresentationMP;
    private javax.swing.JMenu helpMP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
