/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.AdministrateurDAO;
import DAO.ligneCommandeDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Entity.Publicite;
import DAO.publiciteDAO;
import Entity.ligneCommande;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class EspacePub extends javax.swing.JFrame {

    /**
     * Creates new form EspacePub
     */
    public EspacePub() {
        initComponents();
        affiche();
        this.setDefaultCloseOperation(EspacePub.DO_NOTHING_ON_CLOSE);
    }
    
    public void affiche()
    { 
        
        DefaultTableModel tm = (DefaultTableModel) tableEP.getModel();
      
        List<Publicite> services=new ArrayList<Publicite>();
       services=publiciteDAO.getInstance().readAll();
       for (int i = 0; i < services.size(); i++)
       {
       tm.addRow(new Object[] {services.get(i).getDescription(),services.get(i).getDateDebut(),services.get(i).getDateFin(),services.get(i).getPrix()});
       }
       tm.addRow(new Object[] {null,null,null,null});

    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEP = new javax.swing.JTable();
        PanelEP = new javax.swing.JPanel();
        okP = new javax.swing.JButton();
        choixP = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        NouveauPub = new javax.swing.JButton();
        SupprimerPub = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        MenuEP = new javax.swing.JMenuBar();
        FileEP = new javax.swing.JMenu();
        DeconnexionEP = new javax.swing.JMenuItem();
        helpEP = new javax.swing.JMenu();
        PresentationEP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Eespace Publicité");

        tableEP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "description", "date debut", "date fin", "prix"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableEP);
        tableEP.getColumnModel().getColumn(1).setResizable(false);

        PanelEP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        okP.setText("OK");
        okP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okPActionPerformed(evt);
            }
        });

        choixP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activer", "Desactiver" }));
        choixP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixPActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Publicité");

        NouveauPub.setText("Nouveau Publicité");
        NouveauPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NouveauPubActionPerformed(evt);
            }
        });

        SupprimerPub.setText("Supprimer Publicité");
        SupprimerPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerPubActionPerformed(evt);
            }
        });

        jLabel3.setText("Id Pub à supprimer :");

        javax.swing.GroupLayout PanelEPLayout = new javax.swing.GroupLayout(PanelEP);
        PanelEP.setLayout(PanelEPLayout);
        PanelEPLayout.setHorizontalGroup(
            PanelEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEPLayout.createSequentialGroup()
                        .addComponent(choixP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okP, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEPLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t2)
                            .addComponent(SupprimerPub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NouveauPub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))))
            .addGroup(PanelEPLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelEPLayout.setVerticalGroup(
            PanelEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEPLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(PanelEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choixP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(okP))
                .addGap(68, 68, 68)
                .addComponent(NouveauPub)
                .addGap(86, 86, 86)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SupprimerPub)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh-10.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home-icon.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        FileEP.setText("File");

        DeconnexionEP.setText("Deconnexion");
        DeconnexionEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeconnexionEPActionPerformed(evt);
            }
        });
        FileEP.add(DeconnexionEP);

        MenuEP.add(FileEP);

        helpEP.setText("?");

        PresentationEP.setText("Presentation");
        PresentationEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresentationEPActionPerformed(evt);
            }
        });
        helpEP.add(PresentationEP);

        MenuEP.add(helpEP);

        setJMenuBar(MenuEP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choixPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choixPActionPerformed

    private void PresentationEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresentationEPActionPerformed
        // TODO add your handling code here:
        Presentation p=new Presentation();
        this.setVisible(false);
        p.setVisible(true);
    }//GEN-LAST:event_PresentationEPActionPerformed

    private void DeconnexionEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeconnexionEPActionPerformed
        // TODO add your handling code here:
         ConnexionBestDeal cnx = new ConnexionBestDeal();
        this.setVisible(false);
        cnx.setVisible(true);
    }//GEN-LAST:event_DeconnexionEPActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AcceuilBestDeal l=new AcceuilBestDeal();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        EspacePub l=new EspacePub();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void NouveauPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NouveauPubActionPerformed
        // TODO add your handling code here:
         CrudPub l=new CrudPub();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_NouveauPubActionPerformed

    private void SupprimerPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerPubActionPerformed
        // TODO add your handling code here:
         Publicite d=publiciteDAO.getInstance().readByID(Integer.parseInt(t2.getText()));
         System.out.println("fvbgnx "+d.getId());
         boolean b;  
         if(d!=null){
 
        b=publiciteDAO.getInstance().delete(d);
        if(b==true)
            JOptionPane.showMessageDialog(null,"suppresion effectué");
        else
            JOptionPane.showMessageDialog(null,"suppresion non effectué");
     
        }
        else
             JOptionPane.showMessageDialog(null,"Id inexistant");
        t2.setText(null);
    }//GEN-LAST:event_SupprimerPubActionPerformed

    private void okPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okPActionPerformed
        // TODO add your handling code here:
          JOptionPane.showMessageDialog(null,"effectué");
          
    }//GEN-LAST:event_okPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspacePub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspacePub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspacePub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspacePub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EspacePub().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DeconnexionEP;
    private javax.swing.JMenu FileEP;
    private javax.swing.JMenuBar MenuEP;
    private javax.swing.JButton NouveauPub;
    private javax.swing.JPanel PanelEP;
    private javax.swing.JMenuItem PresentationEP;
    private javax.swing.JButton SupprimerPub;
    private javax.swing.JComboBox choixP;
    private javax.swing.JMenu helpEP;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okP;
    private javax.swing.JTextField t2;
    private javax.swing.JTable tableEP;
    // End of variables declaration//GEN-END:variables
}
